<?php

declare(strict_types=1);

namespace Bitrix\Landing\Copilot\Connector\AI\Type;

enum MessageCode: string
{
	case Baas = 'LANDING_REQUEST_LIMITER_ERROR_BAAS_MSGVER_1';
	case Promo = 'LANDING_REQUEST_LIMITER_ERROR_PROMO_MSGVER_1';
	case Daily = 'LANDING_REQUEST_LIMITER_ERROR_DAILY_MSGVER_1';
	case Monthly = 'LANDING_REQUEST_LIMITER_ERROR_MONTHLY_MSGVER_1';
	case Rate = 'LANDING_REQUEST_LIMITER_ERROR_RATE_MSGVER_1';
	case CloudRegistration = 'LANDING_REQUEST_LIMITER_ERROR_CLOUD_REGISTRATION';
	case Market = 'LANDING_REQUEST_LIMITER_ERROR_MARKET_MSGVER_1';
	case BaasRateLimit = 'LANDING_REQUEST_LIMITER_ERROR_BAAS_RATE_LIMIT_MSGVER_1';
}
