memory_limit = 256M
max_execution_time = 300
upload_max_filesize = 64M
post_max_size = 64M
date.timezone = Europe/Moscow
mbstring.func_overload = 2
max_input_vars = 10000

; --- Opcache (dev-режим под Битрикс) ---
opcache.enable = 1
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 100000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
opcache.save_comments = 1
opcache.fast_shutdown = 1