
CREATE TABLE b_report (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  OWNER_ID varchar(20),
  TITLE varchar(255) NOT NULL,
  DESCRIPTION text,
  CREATED_DATE timestamp NOT NULL,
  CREATED_BY int8 NOT NULL,
  SETTINGS text,
  MARK_DEFAULT int,
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_report_owner_id ON b_report (owner_id);

CREATE TABLE IF NOT EXISTS b_report_sharing (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  REPORT_ID int NOT NULL DEFAULT 0,
  ENTITY varchar(50) NOT NULL,
  RIGHTS varchar(50) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_report_sharing_entity ON b_report_sharing (entity);
CREATE INDEX ix_b_report_sharing_report_id ON b_report_sharing (report_id);

CREATE TABLE IF NOT EXISTS b_report_visual_report_widget (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  GID varchar(255) NOT NULL,
  VIEW_KEY varchar(255) NOT NULL,
  WIDGET_CLASS varchar(255) NOT NULL,
  BOARD_ID varchar(255) NOT NULL,
  DASHBOARD_ROW_ID int NOT NULL,
  WEIGHT varchar(25) NOT NULL DEFAULT '',
  CATEGORY_KEY varchar(255) NOT NULL DEFAULT '',
  OWNER_ID int NOT NULL DEFAULT 0,
  IS_PATTERN smallint DEFAULT 0,
  PARENT_WIDGET_ID int NOT NULL DEFAULT 0,
  CREATED_DATE timestamp NOT NULL,
  UPDATED_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_report_visual_report_widget_board_id ON b_report_visual_report_widget (board_id);

CREATE TABLE IF NOT EXISTS b_report_visual_report_entity (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  GID varchar(255) NOT NULL,
  WIDGET_ID int NOT NULL,
  WEIGHT int NOT NULL DEFAULT 0,
  REPORT_CLASS varchar(255),
  CREATED_DATE timestamp NOT NULL,
  UPDATED_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_report_visual_report_entity_widget_id ON b_report_visual_report_entity (widget_id);

CREATE TABLE IF NOT EXISTS b_report_visual_report_configuration (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  GID varchar(255) NOT NULL,
  WEIGHT int NOT NULL DEFAULT 0,
  CREATED_DATE timestamp NOT NULL,
  UPDATED_DATE timestamp NOT NULL,
  UKEY varchar(255) NOT NULL,
  CONFIGURATION_FIELD_CLASS varchar(255) NOT NULL,
  SETTINGS text,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_report_visual_report_entity_config (
  REPORT_ID int NOT NULL,
  CONFIGURATION_ID int NOT NULL,
  PRIMARY KEY (REPORT_ID, CONFIGURATION_ID)
);
CREATE INDEX ix_b_report_visual_report_entity_config_configuration_id_report ON b_report_visual_report_entity_config (configuration_id, report_id);

CREATE TABLE IF NOT EXISTS b_report_visual_report_widget_config (
  WIDGET_ID int NOT NULL,
  CONFIGURATION_ID int NOT NULL,
  PRIMARY KEY (WIDGET_ID, CONFIGURATION_ID)
);
CREATE INDEX ix_b_report_visual_report_widget_config_configuration_id_widget ON b_report_visual_report_widget_config (configuration_id, widget_id);

CREATE TABLE IF NOT EXISTS b_report_visual_report_dashboard_row (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  GID varchar(255) NOT NULL,
  BOARD_ID int NOT NULL,
  WEIGHT int NOT NULL DEFAULT 0,
  CREATED_DATE timestamp NOT NULL,
  UPDATED_DATE timestamp NOT NULL,
  LAYOUT_MAP text NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_report_visual_report_dashboard (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  GID varchar(255) NOT NULL,
  VERSION varchar(255) NOT NULL DEFAULT '',
  BOARD_KEY varchar(255) NOT NULL,
  USER_ID int NOT NULL DEFAULT 0,
  CREATED_DATE timestamp NOT NULL,
  UPDATED_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
);
